<a href="https://colab.research.google.com/github/Jaydeep-2000/ML/blob/main/Linear%20Regression%20/%20MultiLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [3]:
path = "https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv"

In [4]:
df = pd.read_csv(path)

In [5]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [7]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
x = df[['area', 'bedrooms', 'age']]
y = df['price']


In [9]:
lm = linear_model.LinearRegression()
lm.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
lm.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
lm.intercept_

221323.00186540396

In [12]:
lm.predict([[3000,3,40]])

array([498408.25158031])

In [13]:
lm.predict([[2500,4,5]])

array([578876.03748933])

In [1]:
import pickle

In [14]:
with open('model_pickle','wb') as f:
  pickle.dump(lm, f)

In [15]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [19]:
mp.predict([[2500,4,5]])

array([578876.03748933])

In [16]:
from sklearn.externals import joblib

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [17]:
joblib.dump(lm, 'model_joblib')

['model_joblib']

In [18]:
mj = joblib.load('model_joblib')

In [20]:
mj.predict([[2500,4,5]])

array([578876.03748933])