<a href="https://colab.research.google.com/github/Jaydeep-2000/ML/blob/main/Linear%20Regression/%20MultiLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [2]:
path = "https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv"

In [3]:
df = pd.read_csv(path)

In [4]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [14]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [15]:
x = df[['area', 'bedrooms', 'age']]
y = df['price']


In [16]:
lm = linear_model.LinearRegression()
lm.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
lm.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
lm.intercept_

221323.00186540396

In [22]:
lm.predict([[3000,3,40]])

array([498408.25158031])

In [23]:
lm.predict([[2500,4,5]])

array([578876.03748933])